remove install job

diff --git a/.github/workflows/eks-setup.yaml b/.github/workflows/eks-setup.yaml
--- a/.github/workflows/eks-setup.yaml
+++ b/.github/workflows/eks-setup.yaml
@@ -62,26 +62,7 @@ jobs:
         echo "Error: EC2 Public IP is empty. Exiting."
         exit 1    
 
-    - name: Verify EC2 Instance State 
-      run: |
-        INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids $(terraform output -raw ec2_instance_id) --query 'Reservations[*].Instances[*].State.Name' --output text)  
-        echo "EC2 Instance State: $INSTANCE_STATE"
-        if [[ "$INSTANCE_STATE" != "running" ]]; then
-          echo "Error: EC2 instance is not running."
-          exit 1
-        fi    
-
-  InstallTools:
-    runs-on: ubuntu-latest
-    needs: TerraformApply
-    steps:
-    #- name: Set AWS Environment Variables
-      #run: |
-        #echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
-        #echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
-        #echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
-
-    - name: Install SSH Client
+      - name: Install SSH Client
       run: sudo apt-get update && sudo apt-get install -y sshpass
 
     - name: Setup SSH Key
@@ -114,4 +95,25 @@ jobs:
           mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
           kubectl version --client
           aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
-        EOF
+        EOF    
+
+    - name: Verify EC2 Instance State 
+      run: |
+        INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids $(terraform output -raw ec2_instance_id) --query 'Reservations[*].Instances[*].State.Name' --output text)  
+        echo "EC2 Instance State: $INSTANCE_STATE"
+        if [[ "$INSTANCE_STATE" != "running" ]]; then
+          echo "Error: EC2 instance is not running."
+          exit 1
+        fi    
+
+  #InstallTools:
+   # runs-on: ubuntu-latest
+   # needs: TerraformApply
+   # steps:
+    #- name: Set AWS Environment Variables
+      #run: |
+        #echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
+        #echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+        #echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
+
+  
